apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: app-db
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: app-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi